# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/c9ltechn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/c9ltechn/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/c9ltechn/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/c9ltechn/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/c9ltechn/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/c9ltechn/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/c9ltechn/proprietary/bin/tftp_server:system/bin/tftp_server \
    vendor/samsung/c9ltechn/proprietary/etc/camera/msm8976_camera_c9lte.xml:system/etc/camera/msm8976_camera_c9lte.xml \
    vendor/samsung/c9ltechn/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/samsung/c9ltechn/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/samsung/c9ltechn/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
	vendor/samsung/c9ltechn/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
	vendor/samsung/c9ltechn/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/samsung/c9ltechn/proprietary/etc/nfc/sec_s3nrn81_rfreg.bin:system/etc/nfc/sec_s3nrn81_rfreg.bin \
    vendor/samsung/c9ltechn/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/c9ltechn/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libprotobuf-cpp-full.so:system/lib64/libprotobuf-cpp-full.so \
    vendor/samsung/c9ltechn/proprietary/lib64/librmnetctl.so:system/lib64/librmnetctl.so \
    vendor/samsung/c9ltechn/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/c9ltechn/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/c9ltechn/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libsecril-client.so:system/lib64/libsecril-client.so \
    vendor/samsung/c9ltechn/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/c9ltechn/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/c9ltechn/proprietary/lib64/librilutils.so:system/lib64/librilutils.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/c9ltechn/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/c9ltechn/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libsec-ril-dsds.so:system/lib64/libsec-ril-dsds.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
    vendor/samsung/c9ltechn/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/samsung/c9ltechn/proprietary/vendor/firmware/nfc/sec_s3nrn81_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn81_firmware.bin
