# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/c9ltechn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/c9ltechn/proprietary/lib64/libsec-ril.so:system/vendor/lib64/libsec-ril.so \
    vendor/samsung/c9ltechn/proprietary/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/c9ltechn/proprietary/bin/pm-proxy:system/bin/pm-proxy \
    vendor/samsung/c9ltechn/proprietary/bin/pm-service:system/bin/pm-service \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/samsung/c9ltechn/proprietary/lib64/libfloatingfeature.so:system/vendor/lib64/libfloatingfeature.so \
    vendor/samsung/c9ltechn/proprietary/lib/libfloatingfeature.so:system/vendor/lib/libfloatingfeature.so \
    vendor/samsung/c9ltechn/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/samsung/c9ltechn/proprietary/lib64/hw/sensors.msm8952.so:system/lib64/hw/sensors.msm8952.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libyasalgo.so:system/vendor/lib64/libyasalgo.so \
    vendor/samsung/c9ltechn/proprietary/bin/ipacm-diag:system/bin/ipacm-diag \
    vendor/samsung/c9ltechn/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/c9ltechn/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/c9ltechn/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/c9ltechn/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/c9ltechn/proprietary/bin/tftp_server:system/bin/tftp_server \
    vendor/samsung/c9ltechn/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/samsung/c9ltechn/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/samsung/c9ltechn/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/samsung/c9ltechn/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/c9ltechn/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/c9ltechn/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/samsung/c9ltechn/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/c9ltechn/proprietary/vendor/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/vendor/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/samsung/c9ltechn/proprietary/etc/nfc/sec_s3nm81_rfreg.com:system/etc/nfc/sec_s3nm81_rfreg.com \
    vendor/samsung/c9ltechn/proprietary/vendor/firmware/nfc/sec_s3nrn81_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn81_firmware.bin
